= edj

Edj (pronounced like the English word "edge") is the skeleton of 
a simple line editor patterned after Unix ed(1).

It was not created to be a useful editor - _you cannot yet save!_ - but to
provide a platform for some demonstrations of Design Patterns in the Java
language, notably the "undo" command. If someone (or even me) tries to turn
it into a useful line editor, you'll know that CLI fans have regained the
upper hand in geekdom. Or not.

It was also written to show that you can, in fact, do something small and 
(possibly) useful without dragging in 47 different add-on JAR files.

== Usage

* Compile and package:
----
	mvn package
----
* Copy the _edj_ script to a directory on your path 
(on MS-DOS-derived systems, copy it to _edj.bat_ and check the line endings).
* Copy the JAR file from _target/_ to someplace like $HOME/lib/
* Hack the _edj_ script to find the jar file there.


Invoke with a filename argument.

Commands are single lower-case letters (or '.' or '=')
Command lines are of the form _start_,_end_++COMMAND++_operands_

The line range _start_,_end_ is optional; if omitted altogether the
current line (most recendly added or modified) is meant.
If only one line is intended, omit the comma and the second number.
A command line that consists only of a line number will move the current line to that number.

The special line number '$' is not implemented.

The following commands are implemented so far:

[[commands]]
.Implemented Commands
[options="header",cols="2,3,5"]
|====
|Name|Stands for|Notes
|.|Current|Print the current line
|=|Line numbers|What are current and dollar(last-line) equal to?
|a|append|Type lines, end with "." on line by itself
|d|delete|
|e|edit|load a new file and make it the current file
|f|filename|Print the current filename (does not set it)
|q|quit|Does not currently prompt for unsaved changes
|r|read|read named file into buffer
|u|undo|Undoes last modify command
|====

The following are NOT yet implemented:

[[unimplemented-commands]]
.Unimplemented Commands
.The Main Source Repositories
[options="header",cols="2,3,5"]
|====
|Name|Stands for|Notes
|b||
|c|change|combines delet with append
|g|global|
|h|-|
|i|insert|Like a but inserts before current line
|j|join|merge current line and next line into one line
|k|-|
|l|list|Like p but expands unprintable characters
|m|move|
|n|-|
|o|-|
|s|substitute|\[linerange]s/old/new/[g] - replace old (regex) with new (text), once per line unless g
|t|-|
|v|inVert|like g but does non-matching lines
|w|write|write to current file if any, or named file
|x|?|encrypt file
|y|-|
|z|-|
|:|extention|That would start down the path from _ed_ to _ex_, and then _vi_. Not on my watch.
|====
